[package]
name = "todo-fs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.1"
log = "0.4.20"
rusqlite = "0.30.0"
thiserror = "1.0.56"

[build-dependencies]
bindgen = "0.69.1"
